theme: jekyll-theme-slate
title: AZ-204 - Training - Developing Solutions for Microsoft Azure
description: Companion material and resources for the course 'Developing Solutions for Microsoft Azure' delivery by Ricardo Cabral. 
relative_links:
  enabled: true
  collections: true
include:
  - README.md
